// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Arena: typeof import('./src/components/Arena.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    SelectCharacter: typeof import('./src/components/SelectCharacter.vue')['default']
  }
}

export { }
